meta_product_name: "in-frieden.ch"
meta_title: "in-frieden.ch - Traueranzeigen online teilen"
meta_description: "Erstellen und teilen sie eine dynamische Todesanzeige ihrer geliebten Person."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards