meta_product_name: "in-frieden.ch"
meta_title: "in-frieden.ch - Traueranzeigen erleichtert"
meta_description: "in-frieden.ch erleichtert den Prozess der Schaltung von Todesanzeigen in Zeitungen und ist dabei auch noch günstiger"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards